/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XcodeSetupRouteImport } from './routes/xcode-setup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuranIndexRouteImport } from './routes/quran.index'
import { Route as QuranSurahRouteImport } from './routes/quran.$surah'
import { Route as ApiPublicCronFajrPushRouteImport } from './routes/api/public/cron/fajr-push'

const XcodeSetupRoute = XcodeSetupRouteImport.update({
  id: '/xcode-setup',
  path: '/xcode-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranIndexRoute = QuranIndexRouteImport.update({
  id: '/quran/',
  path: '/quran/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranSurahRoute = QuranSurahRouteImport.update({
  id: '/quran/$surah',
  path: '/quran/$surah',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronFajrPushRoute = ApiPublicCronFajrPushRouteImport.update({
  id: '/api/public/cron/fajr-push',
  path: '/api/public/cron/fajr-push',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/licenses': typeof LicensesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/xcode-setup': typeof XcodeSetupRoute
  '/quran/$surah': typeof QuranSurahRoute
  '/quran/': typeof QuranIndexRoute
  '/api/public/cron/fajr-push': typeof ApiPublicCronFajrPushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/licenses': typeof LicensesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/xcode-setup': typeof XcodeSetupRoute
  '/quran/$surah': typeof QuranSurahRoute
  '/quran': typeof QuranIndexRoute
  '/api/public/cron/fajr-push': typeof ApiPublicCronFajrPushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/licenses': typeof LicensesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/xcode-setup': typeof XcodeSetupRoute
  '/quran/$surah': typeof QuranSurahRoute
  '/quran/': typeof QuranIndexRoute
  '/api/public/cron/fajr-push': typeof ApiPublicCronFajrPushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/licenses'
    | '/privacy'
    | '/terms'
    | '/xcode-setup'
    | '/quran/$surah'
    | '/quran/'
    | '/api/public/cron/fajr-push'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/licenses'
    | '/privacy'
    | '/terms'
    | '/xcode-setup'
    | '/quran/$surah'
    | '/quran'
    | '/api/public/cron/fajr-push'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/licenses'
    | '/privacy'
    | '/terms'
    | '/xcode-setup'
    | '/quran/$surah'
    | '/quran/'
    | '/api/public/cron/fajr-push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LicensesRoute: typeof LicensesRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  XcodeSetupRoute: typeof XcodeSetupRoute
  QuranSurahRoute: typeof QuranSurahRoute
  QuranIndexRoute: typeof QuranIndexRoute
  ApiPublicCronFajrPushRoute: typeof ApiPublicCronFajrPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xcode-setup': {
      id: '/xcode-setup'
      path: '/xcode-setup'
      fullPath: '/xcode-setup'
      preLoaderRoute: typeof XcodeSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/': {
      id: '/quran/'
      path: '/quran'
      fullPath: '/quran/'
      preLoaderRoute: typeof QuranIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/$surah': {
      id: '/quran/$surah'
      path: '/quran/$surah'
      fullPath: '/quran/$surah'
      preLoaderRoute: typeof QuranSurahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/fajr-push': {
      id: '/api/public/cron/fajr-push'
      path: '/api/public/cron/fajr-push'
      fullPath: '/api/public/cron/fajr-push'
      preLoaderRoute: typeof ApiPublicCronFajrPushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LicensesRoute: LicensesRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  XcodeSetupRoute: XcodeSetupRoute,
  QuranSurahRoute: QuranSurahRoute,
  QuranIndexRoute: QuranIndexRoute,
  ApiPublicCronFajrPushRoute: ApiPublicCronFajrPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
