/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCronFajrPushRouteImport } from './routes/api/public/cron/fajr-push'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronFajrPushRoute = ApiPublicCronFajrPushRouteImport.update({
  id: '/api/public/cron/fajr-push',
  path: '/api/public/cron/fajr-push',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/api/public/cron/fajr-push': typeof ApiPublicCronFajrPushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/api/public/cron/fajr-push': typeof ApiPublicCronFajrPushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/api/public/cron/fajr-push': typeof ApiPublicCronFajrPushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/privacy' | '/api/public/cron/fajr-push'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/privacy' | '/api/public/cron/fajr-push'
  id: '__root__' | '/' | '/privacy' | '/api/public/cron/fajr-push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiPublicCronFajrPushRoute: typeof ApiPublicCronFajrPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/fajr-push': {
      id: '/api/public/cron/fajr-push'
      path: '/api/public/cron/fajr-push'
      fullPath: '/api/public/cron/fajr-push'
      preLoaderRoute: typeof ApiPublicCronFajrPushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ApiPublicCronFajrPushRoute: ApiPublicCronFajrPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
